export const MENU_ITEMS = [
  {
    title: 'Home',
    href: '/',
    isShow: true,
    eventName: 'Pages: Home',
    type: 'Pages',
    isPages: true,
    isSection: false,
    isNavbar: true,
  },
  {
    title: 'Our Projects',
    href: '/projects',
    isShow: true,
    eventName: 'Pages: Our Projects',
    type: 'Pages',
    isPages: true,
    isSection: false,
    isNavbar: true,
  },
  {
    title: 'Why Choose Us',
    href: '#why-choose-us',
    isShow: true,
    eventName: 'Sections: Why Choose Us',
    type: 'Sections',
    isPages: false,
    isSection: true,
    isNavbar: false,
  },
  // {
  //   title: 'App Types',
  //   href: '#app-types',
  //   isShow: true,
  //   eventName: 'Sections: App Types',
  //   type: 'Sections',
  //   isPages: false,
  //   isSection: true,
  //   isNavbar: false,
  // },
  {
    title: 'Tech We Use',
    href: '#tech-we-use',
    isShow: true,
    eventName: 'Sections: Tech We Use',
    type: 'Sections',
    isPages: false,
    isSection: true,
    isNavbar: false,
  },
  {
    title: 'Pricing Plans',
    href: '#pricing-plans',
    isShow: true,
    eventName: 'Sections: Pricing Plans',
    type: 'Sections',
    isPages: false,
    isSection: true,
    isNavbar: false,
  },
  {
    title: 'FAQ',
    href: '#asked-questions',
    isShow: true,
    eventName: 'Sections: FAQ',
    type: 'Sections',
    isPages: false,
    isSection: true,
    isNavbar: false,
  },
];

// {
//   title: 'Why Us',
//   href: '#why-us',
//   isShow: true,
//   eventName: 'Sections: Why Us',
//   type: 'Sections',
//   isPages: false,
// },
// {
//   title: 'App Types',
//   href: '#app-types',
//   isShow: true,
//   eventName: 'Sections: App Types',
//   type: 'Sections',
//   isPages: false,
// },
// {
//   title: 'Our Tech',
//   href: '#our-tech',
//   isShow: true,
//   eventName: 'Sections: Our Tech',
//   type: 'Sections',
//   isPages: false,
// },
// {
//   title: 'Pricing Plans',
//   href: '#pricing-plans',
//   isShow: true,
//   eventName: 'Sections: Pricing Plans',
//   type: 'Sections',
//   isPages: false,
// },
// {
//   title: 'FAQ',
//   href: '#faq',
//   isShow: true,
//   eventName: 'Sections: FAQ',
//   type: 'Sections',
//   isPages: false,
// },

export const SECTION_MENU = [
  {
    key: 'Introduction',
    label: 'Introduction',
    sectionId: 'introduction',
  },
  {
    key: 'Why Choose Us',
    label: 'Why Choose Us',
    sectionId: 'why-choose-us',
  },
  {
    key: 'App Types',
    label: 'App Types',
    sectionId: 'app-types',
  },
  {
    key: 'Tech We Use',
    label: 'Tech We Use',
    sectionId: 'tech-we-use',
  },
  {
    key: 'Pricing Plans',
    label: 'Pricing Plans',
    sectionId: 'pricing-plans',
  },
  {
    key: 'FAQ',
    label: 'FAQ',
    sectionId: 'asked-questions',
  },
  {
    key: 'Contact Us',
    label: 'Contact Us',
    sectionId: 'cta',
  },
];
